### ISSUE TITLE
FBTEE retrieval issue

### ISSUE THREAD

**Issue by linguistcrg** [CentreForDigitalHumanities/edpop-explorer#38] opened 2024-07-30 09:08 UTC
While performing a search of the word "almanac", instead of getting this output:
`Performing query: almanac`

I get the following output:
```
Performing query: SQLPreparedQuery(where_statement='WHERE full_book_title LIKE ?', arguments=['%almanac%'])
EXCEPTION of type 'AttributeError' occurred with message: 'int' object has no attribute 'data'
```

And I don't get any results.

**Comment by tijmenbaarda** [comment] 2024-08-13 14:33
This was caused by a small bug and will be fixed as part of #44.

**Comment by tijmenbaarda** [comment] 2024-08-15 09:01
Closed by #44

**Closed by tijmenbaarda** 2024-08-15 09:01 UTC
